# Example docker-compose file for running this docker container with various options.
# 1. Update the options to suit your needs
# 2. Place the file somewhere like /etc/opt/allhail/bot/ or ~/
version: '3.7'
services:
  migrate:
    image: allhail/bot:latest
    env_file: .env
    command: ["migrate"]
  cfb-trivia:
    image: allhail/bot:latest
    env_file: .env
    command: ["cfb-trivia"]
  pull-gocards-calendar:
    image: allhail/bot:latest
    env_file: .env
    command: ["pull-gocards-calendar"]
  postgres:
    image: postgres:11.5-alpine
    env_file: .env
